imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"

## Enable diagnostic mode
##
diagnosticMode:
  ## @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  ##
  enabled: false
  ## @param diagnosticMode.command Command to override all containers
  ##
  command:
    - sleep
  ## @param diagnosticMode.args Args to override all containers
  ##
  args:
    - infinity

resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 50Mi
  # requests:
  #   cpu: 100m
  #   memory: 30Mi

# Interval to flush output (seconds)
flush: 10

# The log index prefix in Quickwit, which is prepended to the index name.
quickwit:
  logIndexPrefix: "logs-"

## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
config:
  service: |
    [SERVICE]
        Flush               {{ .Values.flush }}
        Daemon              Off
        Log_Level           info
        Parsers_File        /opt/drycc/fluent-bit/etc/fluent-bit/parsers.conf
        Plugins_File        /opt/drycc/fluent-bit/etc/fluent-bit/plugins.conf

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name                tail
        Path                /var/log/containers/*.log
        DB                  /var/log/containers.pos.db
        DB.locking          true
        Offset_Key          offset
        Tag                 kubernetes.*
        Read_from_Head      false
        multiline.parser    docker,cri

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kubernetes.*
        Keep_Log            Off
        Merge_Log           On
        Buffer_Size         0
        Use_Tag_For_Meta    true

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name                quickwit
        Match               kubernetes.*
        Base_URL            http://drycc-quickwit-indexer:7280
        Compress            true
        Index_Name          {{printf "%s{{ %s | default \"%s\" }}" .Values.quickwit.logIndexPrefix ".kubernetes.namespace_name" .Release.Namespace }}
        Buffer_Size         65536
        Json_Date_Key       timestamp
        Json_Date_Format    rfc3399
  ## https://docs.fluentbit.io/manual/pipeline/parsers
  parsers: |
    [PARSER]
        Name                docker
        Format              json
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%L
        Time_Keep           On

    [PARSER] 
        # http://rubular.com/r/tjUt3Awgg4
        Name                cri
        Format              regex
        Regex               ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep           On
  ## https://docs.fluentbit.io/manual/development/golang-output-plugins
  plugins: |
    [PLUGINS]
        Path                /opt/drycc/fluent-bit/lib/out_quickwit.so
