apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: drycc-fluentbit
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-fluentbit
      heritage: drycc
  template:
    metadata:
      name: drycc-fluentbit
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        heritage: drycc
        app: drycc-fluentbit
    spec:
      serviceAccount: drycc-fluentbit
      initContainers:
      - name: drycc-fluentbit-init
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
        - netcat
        - -v
        - -u
        - http://drycc-quickwit-indexer:7280
        {{- include "fluentbit.envs" . | indent 8 }}
      containers:
      - name: drycc-fluentbit
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/fluentbit:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        {{- if .Values.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 10 }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 10 }}
        {{- else }}
        args:
        - fluent-bit
        - --config=/opt/drycc/fluent-bit/etc/fluent-bit/fluent-bit.conf
        {{- end }}
        {{- with index .Values "resources" }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- include "fluentbit.envs" . | indent 8 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: fluentbit-config
          mountPath: /opt/drycc/fluent-bit/etc/fluent-bit
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: fluentbit-config
        configMap:
          name: fluentbit-config
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0
