apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: drycc-logger-fluentbit
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-logger-fluentbit
      heritage: drycc
  template:
    metadata:
      name: drycc-logger-fluentbit
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        heritage: drycc
        app: drycc-logger-fluentbit
    spec:
      serviceAccount: drycc-logger-fluentbit
      initContainers:
      - name: drycc-logger-fluentbit-init
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
        - netcat
        - -v
        - -u
        - $(DRYCC_VALKEY_URL)
        {{- include "fluentbit.envs" . | indent 8 }}
      containers:
      - name: drycc-logger-fluentbit
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/fluentbit:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        {{- if .Values.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 10 }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 10 }}
        {{- end }}
        {{- if or (.Values.limitsCpu) (.Values.limitsMemory)}}
        resources:
          limits:
            {{- if (.Values.limitsCpu) }}
            cpu: {{.Values.limitsCpu}}
            {{- end}}
            {{- if (.Values.limitsMemory) }}
            memory: {{.Values.limitsMemory}}
            {{- end}}
        {{- end}}
        {{- include "fluentbit.envs" . | indent 8 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: logger-fluentbit-config
          mountPath: /opt/drycc/fluent-bit/templates
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: logger-fluentbit-config
        configMap:
          name: logger-fluentbit-config
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0
